# Generated by Django 4.2.2 on 2023-07-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clothmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('cloth_brand', models.TextField()),
            ],
        ),
    ]
